#theme = "hugo-theme-casper"
theme = "casper"
languageCode = "es-ES"
title = "DATO FUTBOL"
baseURL = "http://datofutbol.cl/"
# disqusshortname = "datofutbol"
paginate = 20
Copyright = "2017-2019"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
share = true

[params]
  description = "SOCCER/FOOTBALL ANALYTICS  • DATA SCIENCE • RSTATS"
  cover = "images/Rplot.png"
  author = "Ismael Gomez"
  authorlocation = "Santiago, Chile"
  #authorwebsite = "http://vjeantet.fr"
  #bio= "Cabeza de pelota 1"
  logo = "images/pelota.png"
  googleAnalyticsUserID = "UA-92157714-2"
  #UseDisqus = true
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/datofutbol/lUDA"
  githubName = "Bustami/DatoFutbol"
  twitterName = "DatoFutbol_cl"
  facebookName = "datofutbolCL"
  # linkedinName = ""
  
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  hjsStyle = "default"

#[params.social]
#    twitter = "DatoFutbol_cl"
#    facebook = "datofutbolCL"

[[menu.main]]
  name = "Inicio"
  weight = -90
  identifier = "inicio"
  url = "/"

[[menu.main]]
  name = "About"
  weight = -100
  identifier = "about"
  url = "/about/"
  
  [[menu.main]]
  name = "Chile"
  pre = "<h3>CATEGORIES</h3>"
  weight = -110
  identifier = "chile"
  url = "/categories/chile/"
  
  [[menu.main]]
  name = "Conmebol"
  #pre = "<h3>CATEGORIAS</h3>"
  weight = -120
  identifier = "conmebol"
  url = "/categories/conmebol/"
  
  [[menu.main]]
  name = "Europa"
  #pre = "<h3>CATEGORIAS</h3>"
  weight = -130
  identifier = "europa"
  url = "/categories/europa/"

[[menu.main]]
  name = "English"
  #pre = "<h3>CATEGORIAS</h3>"
  weight = -140
  identifier = "English"
  url = "/categories/english/"
  
[[menu.main]]
  name = "Varios"
  #pre = "<h3>CATEGORIAS</h3>"
  weight = -140
  identifier = "varios"
  url = "/categories/varios/"

[[menu.main]]
  name = "Twitter"
  pre = "<h3>CONTACT</h3>"
  url = "https://twitter.com/DatoFutbol_cl"
  weight = -150

[[menu.main]]
  name = "Facebook"
  #pre = "<h3>CONTACTO</h3>"
  url = "https://www.facebook.com/datofutbolCL/"
  weight = -160
  
[[menu.main]]
  name = "Github"
  url = "https://github.com/Bustami/DatoFutbol"
  weight = -170
 

[permalinks]
post = "/:slug/"
