---
title: "Historical Men FIFA Ranking [april 2019] - English"
description: ''
author: "Ismael Gómez"
lang: es
date: '2019-05-21'
output:
  html_document: default
draft: false
image: false
menu: ''
share: yes
slug: ranking-fifa-historico-last-en
tags:
- RankingFIFA
categories: ["English"]
---


```{r global_options, include=F}
knitr::opts_chunk$set(echo=F, warning=FALSE, message=FALSE)
library(kableExtra)
library(dplyr)
library(knitr)
```

I just updated the Shiny app which allows you visualize the historical Men FIFA ranking, this time including last data officially published (april 2019). Enjoy it!

Top 10 Men FIFA Ranking:

```{r c1}
data <- read.csv("ranking_shiny.csv") %>% 
        filter(ye==2019 & mo==4 & Rank<11) %>%
        select("Rank", "Team")

kable(data, "html", align='c') %>%
  kable_styling(full_width=F, bootstrap_options = c("basic"))
```

***  

App:

<iframe width="900" height="750" scrolling="yes" frameborder="no"  src="https://bustami.shinyapps.io/ranking_fifa/"> </iframe>

```{r c2}
#knitr::include_app("https://bustami.shinyapps.io/ranking_fifa/", height = "750px")
```




